### ISSUE TITLE
Cannot build v2.3.1: Cannot find rocm library hip_hcc

### ISSUE THREAD

**Issue by eugeneswalker** [ROCmSoftwarePlatform/tensorflow-upstream#1157]
I'm trying to build `ROCmSoftwarePlatform/tensorflow-upstream` at `v2.3.1` with ROCm support inside a Docker container.

* `Ubuntu 18.04` docker container, `x86_64`
* Using apt repo: `deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main`
   a. `apt install rocm-dev rocm-libs rccl`
   b. apt installed the other packages listed:
       https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/rocm-terminal/Dockerfile
 * `bazel@3.1.0`
 * `python@3.6.9`
 * `docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video ...`
 * `/opt/rocm/bin/rocminfo` inside the container shows Vega 20 (x2)

```
$> git clone https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git
$> cd tensorflow-upstream
$> ./configure
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]:

Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]:
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: y
ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]:
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -march=x86-64 -Wno-sign-compare

....
Configuration finished

$> bazel build --config=rocm --config=opt //tensorflow/tools/pip_package:build_pip_package
...
Repository rule rocm_configure defined at:
  /tensorflow-upstream/third_party/gpus/rocm_configure.bzl:866:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 845
		_create_local_rocm_repository(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 652, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 453, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 422, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 845
		_create_local_rocm_repository(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 652, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 453, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 422, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 845
		_create_local_rocm_repository(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 652, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 453, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 422, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
INFO: Elapsed time: 0.227s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

Indeed, I do not have libhip_hcc installed.

What apt package provides this, if not `rocm-dev rocm-libs rccl` ??

Are there instructions for building rocm-tensorfow wheel from source using `ROCmSoftwarePlatform/tensorflow-upstream` ?

**Comment by eugeneswalker** [comment]
Any update on this?

What package provides `libhip_hcc` ? Is this deprecated?

Does ROCM 3.8 not work with recent TensorFlow releases?

**Comment by xuhuisheng** [comment]
@eugeneswalker hip_hcc is replaced by hip - /opt/rocm/hip/lib/libamdhip64.so. Maybe create a symbolic like ln -s /opt/rocm/lib/libhip_hcc.so /opt/rocm/hip/lib/libamdhip64.so

**Comment by eugeneswalker** [comment]
> @eugeneswalker hip_hcc is replaced by hip - /opt/rocm/hip/lib/libamdhip64.so. Maybe create a symbolic like ln -s /opt/rocm/lib/libhip_hcc.so /opt/rocm/hip/lib/libamdhip64.so

OK. I will do this.

Can you please link me to the official documentation for installing the ROCM libraries needed to build TensorFlow?

**Comment by jerryyin** [comment]
@eugeneswalker Please feel free to use the pre-configured dockers under `rocm/tensorflow` channel. Also, for full dependencies please refer to [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md).

**Comment by ppanchad-amd** [comment]
Hi @eugeneswalker. Hope your issue is resolved. We will be closing this ticket.  Please feel free to open another ticket if you have any issues/questions with the latest ROCm. Thanks!
