### ISSUE TITLE
MiOpen: Internal error while accessing SQLite database: disk I/O error

### ISSUE THREAD

**Issue by dipietrantonio** [ROCmSoftwarePlatform/tensorflow-upstream#1419]
**System information**
- I am trying the tensorflow beginner tutorial on the MNIST dataset.
- OS Platform and Distribution: sles15sp2
- TensorFlow installed from (source or binary): singularity container converted from docker.
- TensorFlow version (use command below): tensorflow_rocm4.2-tf2.5-dev.sif
- Python version: 3.6.9
- GPU model and memory: gfx908, 32gb

I run the container using the following command
```
singularity exec --writable-tmpfs --rocm -B `pwd`:$HOME tensorflow_rocm4.2-tf2.5-dev.sif bash
```

**Error**
When running the python script, I get the following error
```
MIOpen(HIP): Warning [FindWinogradSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindDataDirectSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindFftSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
2021-08-10 15:21:54.882523: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
MIOpen Error: /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error

```

The entire output is:
```
Singularity> python3 main.py 
2021-08-10 15:21:44.650831: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libamdhip64.so
2021-08-10 15:21:45.558089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: Device 738c     ROCm AMDGPU Arch: gfx908:sramecc+:xnack-
coreClock: 1.502GHz coreCount: 120 deviceMemorySize: 31.98GiB deviceMemoryBandwidth: 1.12TiB/s
2021-08-10 15:21:45.558708: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-08-10 15:21:45.569868: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-08-10 15:21:46.694944: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-08-10 15:21:46.703200: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-08-10 15:21:46.703330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-08-10 15:21:46.704317: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-10 15:21:46.718679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: Device 738c     ROCm AMDGPU Arch: gfx908:sramecc+:xnack-
coreClock: 1.502GHz coreCount: 120 deviceMemorySize: 31.98GiB deviceMemoryBandwidth: 1.12TiB/s
2021-08-10 15:21:46.718745: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-08-10 15:21:46.718768: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-08-10 15:21:46.718779: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-08-10 15:21:46.718790: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-08-10 15:21:46.718844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-08-10 15:21:46.718924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-10 15:21:46.718937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-08-10 15:21:46.718944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-08-10 15:21:46.719081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 32252 MB memory) -> physical GPU (device: 0, name: Device 738c, pci bus id: 0000:29:00.0)
2021-08-10 15:21:47.841600: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-08-10 15:21:47.864112: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1996360000 Hz
2021-08-10 15:21:47.898988: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:507] ROCm Fusion is enabled.
2021-08-10 15:21:47.937976: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
MIOpen(HIP): Warning [FindWinogradSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindDataDirectSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
MIOpen(HIP): Warning [FindFftSolutions] /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
2021-08-10 15:21:54.882523: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
MIOpen Error: /root/driver/MLOpen/src/sqlite_db.cpp:212: Internal error while accessing SQLite database: disk I/O error
2021-08-10 15:21:55.007966: F tensorflow/stream_executor/rocm/rocm_dnn.cc:3511] call to miopenConvolutionBackwardWeightsAlgorithm failed: miopenStatusInternalError
Aborted (core dumped)

```

A similar error is happening in pytorch: https://github.com/pytorch/pytorch/issues/60477

**Comment by sunway513** [comment]
Hi @dipietrantonio , it seems the issue is due to lack of local storage for MIOpen runtime.
@JehandadKhan , could you help comment if there's any option in MIOpen to workaround the issue?

**Comment by dipietrantonio** [comment]
I have solved this issue with using the singularity flag "--fake-root". It was a permissions error. However this solution makes singularity "unpack" the image into a writable directory, which is not ideal.

At the moment I am trying to build a rocm + tensorflow container for singularity from scratch, but I find it quite hard.

**Comment by JehandadKhan** [comment]
@dipietrantonio Thanks for triaging the issue further. Can I ask you to conduct two experiments? 

1. Using the test case where you see failures, please export the env var `MIOPEN_LOG_LEVEL=7` and share the generated logs here. This should give us detailed information about what is going on behind the scenes and enable us to help you better.
2. I agree with your synopsis, that its a file system issue. To avoid unpacking the entire image, can you export the following environment variable `MIOPEN_USER_DB_PATH="/tmp"` This would instruct MIOpen to use the TEMP directory instead of your home directory which I believe is mounted on a share.

Please let me know of the outcome so we can resolve the issue.

**Comment by Felix-Petersen** [comment]
#https://github.com/pytorch/pytorch/issues/60477

**Comment by dipietrantonio** [comment]
@JehandadKhan sorry for the late reply. So, after a few more experiments, it appears it is indeed because of the lack of space in `/tmp`. We can close the issue now, and if I encounter the same behaviour I will let you know.

Cheers
Cristian

**Comment by chn-lee-yumi** [comment]
Using `MIOPEN_USER_DB_PATH="/tmp"` fix my problem. Thanks!
