### ISSUE TITLE
Unable to find a suitable algorithm for doing forward convolution

### ISSUE THREAD

**Issue by Sumenia** [ROCmSoftwarePlatform/tensorflow-upstream#142]
Hi, I get a weird error about `Unable to find a suitable algorithm for doing forward convolution` when I run the session.
From what I understand, there is a kernel compiled with `-DLOCAL_MEM_SIZE=19008` that is not something coming from my code. Even with a batch size of 1 I get the same error. 

```
ml_1  | 2018-08-23 21:03:11.045474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
ml_1  | name: Device 687f
ml_1  | AMDGPU ISA: gfx900
ml_1  | memoryClockRate (GHz) 1.63
ml_1  | pciBusID 0000:0c:00.0
ml_1  | Total memory: 7.98GiB
ml_1  | Free memory: 7.73GiB
ml_1  | 2018-08-23 21:03:11.045489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0
ml_1  | 2018-08-23 21:03:11.045503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
ml_1  | 2018-08-23 21:03:11.045510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0
ml_1  | 2018-08-23 21:03:11.045516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N
ml_1  | 2018-08-23 21:03:11.045547: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Device 687f, pci bus id: 0000:0c:00.0)
ml_1  | 2018-08-23 21:03:26.581328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0
ml_1  | 2018-08-23 21:03:26.581382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
ml_1  | 2018-08-23 21:03:26.581396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0
ml_1  | 2018-08-23 21:03:26.581407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N
ml_1  | 2018-08-23 21:03:26.581440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Device 687f, pci bus id: 0000:0c:00.0)
ml_1  | 2018-08-23 21:04:20.430885: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | 2018-08-23 21:04:20.495395: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | 2018-08-23 21:04:20.557689: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | error: local memory limit exceeded (76032) in Im2Col
ml_1  | MIOpen Error: /data/repo/MIOpen/src/tmp_dir.cpp:18: Can't execute cd /tmp/miopen-MIOpenUtilKernels.cl-faa6-605d-295b-fc2e; /opt/rocm/bin/clang-ocl  -DNUM_CH_PER_WG=1 -DNUM_IM_BLKS_X=3 -DNUM_IM_BLKS=9 -DLOCAL_MEM_SIZE=19008 -DSTRIDE_GT_1=1 -DTILE_SZ_X=32 -DTILE_SZ_Y=8 -DUSE_IM_OFF_GUARD=1 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -mcpu=gfx900 -Wno-everything MIOpenUtilKernels.cl -o /tmp/miopen-MIOpenUtilKernels.cl-faa6-605d-295b-fc2e/MIOpenUtilKernels.cl.o
ml_1  | 2018-08-23 21:04:20.879002: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1803] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
ml_1  | [I 21:04:21.291 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
ml_1  | WARNING:root:kernel 0d0fea33-23e8-4e97-8fa9-0bda0c19ea6f restarted
ml_1  | [I 21:04:37.435 NotebookApp] Saving file at /Road Segmentation.ipynb
```

**Comment by whchung** [comment]
Looks like an issue in MIOpen GEMM-based convolution kernel. Could you help collect the configuration by running tensorflow with one environmental variable

MIOPEN_ENABLE_LOGGING_CMD=1

**Comment by Sumenia** [comment]
```
ml_1  | 2018-08-23 21:38:18.296805: W tensorflow/stream_executor/rocm/rocm_driver.cc:404] creating context when one is currently active; existing: 0x7fb721a11370
ml_1  | 2018-08-23 21:38:18.297134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
ml_1  | name: Device 687f
ml_1  | AMDGPU ISA: gfx900
ml_1  | memoryClockRate (GHz) 1.63
ml_1  | pciBusID 0000:0c:00.0
ml_1  | Total memory: 7.98GiB
ml_1  | Free memory: 7.73GiB
ml_1  | 2018-08-23 21:38:18.297173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0
ml_1  | 2018-08-23 21:38:18.297198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
ml_1  | 2018-08-23 21:38:18.297210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0
ml_1  | 2018-08-23 21:38:18.297218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N
ml_1  | 2018-08-23 21:38:18.297258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Device 687f, pci bus id: 0000:0c:00.0)
ml_1  | 2018-08-23 21:38:29.288390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0
ml_1  | 2018-08-23 21:38:29.288456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
ml_1  | 2018-08-23 21:38:29.288471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0
ml_1  | 2018-08-23 21:38:29.288490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N
ml_1  | 2018-08-23 21:38:29.288545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Device 687f, pci bus id: 0000:0c:00.0)
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 3 -H 160 -W 576 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 3 -H 160 -W 576 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 64 -H 160 -W 576 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 64 -H 160 -W 576 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 64 -H 80 -W 288 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 64 -H 80 -W 288 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 128 -H 80 -W 288 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 128 -H 80 -W 288 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 128 -H 40 -W 144 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 128 -H 40 -W 144 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 40 -W 144 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 40 -W 144 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 40 -W 144 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 20 -W 72 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 20 -W 72 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 20 -W 72 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 256 -H 20 -W 72 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 20 -W 72 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 20 -W 72 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 20 -W 72 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 10 -W 36 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 5 -W 18 -k 4096 -y 7 -x 7 -p 3 -q 3 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 512 -H 5 -W 18 -k 4096 -y 7 -x 7 -p 3 -q 3 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 4096 -H 5 -W 18 -k 4096 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 4096 -H 5 -W 18 -k 4096 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 4096 -H 5 -W 18 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionForward: ./bin/MIOpenDriver conv -n 32 -c 4096 -H 5 -W 18 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -t 1
ml_1  | 2018-08-23 21:38:58.247656: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 10 -W 36 -k 2 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 10 -W 36 -k 2 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -t 1
ml_1  | 2018-08-23 21:38:58.798257: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 20 -W 72 -k 2 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 20 -W 72 -k 2 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -t 1
ml_1  | 2018-08-23 21:38:59.127857: I tensorflow/core/kernels/conv_grad_input_ops.cc:1007] running auto-tune for Backward-Data
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 160 -W 576 -k 2 -y 16 -x 16 -p 4 -q 4 -u 8 -v 8 -l 1 -j 1 -t 1
ml_1  | miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 32 -c 2 -H 160 -W 576 -k 2 -y 16 -x 16 -p 4 -q 4 -u 8 -v 8 -l 1 -j 1 -t 1
ml_1  | error: local memory limit exceeded (76032) in Im2Col
ml_1  | MIOpen Error: /data/repo/MIOpen/src/tmp_dir.cpp:18: Can't execute cd /tmp/miopen-MIOpenUtilKernels.cl-5f68-bac0-6ca5-33b6; /opt/rocm/bin/clang-ocl  -DNUM_CH_PER_WG=1 -DNUM_IM_BLKS_X=3 -DNUM_IM_BLKS=9 -DLOCAL_MEM_SIZE=19008 -DSTRIDE_GT_1=1 -DTILE_SZ_X=32 -DTILE_SZ_Y=8 -DUSE_IM_OFF_GUARD=1 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -mcpu=gfx900 -Wno-everything MIOpenUtilKernels.cl -o /tmp/miopen-MIOpenUtilKernels.cl-5f68-bac0-6ca5-33b6/MIOpenUtilKernels.cl.o
ml_1  | 2018-08-23 21:38:59.714117: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1803] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
ml_1  | [I 21:39:00.122 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
ml_1  | WARNING:root:kernel 7115154d-dd20-4964-ac6f-419d6a789a24 restarted
```

**Comment by whchung** [comment]
@Sumenia I've verified this configuration indeed fails:

```
./bin/MIOpenDriver conv -n 32 -c 2 -H 160 -W 576 -k 2 -y 16 -x 16 -p 4 -q 4 -u 8 -v 8 -l 1 -j 1 -t 1
```

with both publicly released version of MIOpen or internal develop branch. I've raised a ticket with MIOpen team.

**Comment by whchung** [comment]
according to https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/MIOpen-Environment-Variables there are ways to disable different flavors of convolution algorithms. Unfortunately GEMM-based algorithms can't be disabled.

**Comment by whchung** [comment]
a fix has been derived by @ce1adon who works on MIOpen.

@ce1adon / @daniellowell , would this fix be able to make its way into upcoming ROCm 1.9 release?

**Comment by daniellowell** [comment]
@whchung Yes, potentially. It depends on when 1.9 is slated for actual release.

**Comment by Sumenia** [comment]
@whchung @daniellowell I just tried again with rocm 1.9 (`rocm1.9.0-tf1.8-python3-dev`) and this error still occurs. I assume that the fix from MIOpen didn't make it into Rocm 1.9 release ?

**Comment by daniellowell** [comment]
@Sumena can tou check your MIOpen install version? In /opt/rocm/miopen/include/version.h

**Comment by dagamayank** [comment]
@Sumenia I have verified that the issue we were stumbling upon before has been fixed in MIOpen 1.5 on a 8GB AMD "Vega" GPU, which is released as part of ROCm 1.9. 

```
$ ./bin/MIOpenDriver conv -n 32 -c 2 -H 160 -W 576 -k 2 -y 16 -x 16 -p 4 -q 4 -u 8 -v 8 -l 1 -j 1 -t 1
MIOpenDriver: conv -n 32 -c 2 -H 160 -W 576 -k 2 -y 16 -x 16 -p 4 -q 4 -u 8 -v 8 -l 1 -j 1 -t 1
MIOpen Forward Conv. Algorithm: 0
GPU Kernel Time Forward Conv. Elapsed: 5.850370 ms
Forward Convolution Verifies on CPU and GPU (6.10705e-08)
MIOpen Backward Data Conv. Algorithm: 0
GPU Kernel Time Backward Data Conv. Elapsed: 1.358114 ms
MIOpen Backward Weights Conv. Algorithm: 0
GPU Kernel Time Backward Weights Conv. Elapsed: 5.628881 ms
Backward Convolution Data Verifies on CPU and GPU (1.00745e-08)
Backward Convolution Weights Verifies on CPU and GPU (2.11889e-07)
```

It might be possible that we are now running into a new albeit similar problem. If you confirm that you are on MIOpen 1.5, can you please run your test again with the following env. variable set and report back.
`export MIOPEN_ENABLE_LOGGING_CMD=1`

**Comment by Sumenia** [comment]
I ran it with the new docker image from docker hub but I forgot to update the host to rocm 1.9 too 😅

is the last package from apt correct ? or is repo.radeon.com down ? because i can't update via apt: 
`E: Failed to fetch http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-dkms/rocm-dkms_1.9.211_amd64.deb  Connection failed [IP: 13.82.220.49 80]`

and quick checking via web browsing is the same: http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-dkms/rocm-dkms_1.9.211_amd64.deb

**Comment by tadaoisgod** [comment]
I've just stumbled upon the same error while trying to run YOLOv3 inferences from [this repository](https://github.com/qqwweee/keras-yolo3). 

```bash
$ python yolo_video.py --input /data/tests/generic_detector/car_0.jpg --image
/home/tadao/.virtualenvs/amd/local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Image detection mode
 Ignoring remaining command line arguments: /data/tests/generic_detector/car_0.jpg,
2018-09-28 17:45:04.829246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1519] Found device 0 with properties: 
name: Device 67df
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1.288
pciBusID 0000:09:00.0
Total memory: 8.00GiB
Free memory: 7.75GiB
2018-09-28 17:45:04.829290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1630] Adding visible gpu devices: 0
2018-09-28 17:45:04.829306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1039] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-28 17:45:04.829316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045]      0 
2018-09-28 17:45:04.829325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1058] 0:   N 
2018-09-28 17:45:04.829363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7539 MB memory) -> physical GPU (device: 0, name: Device 67df, pci bus id: 0000:09:00.0)
model_data/yolo.h5 model, anchors, and classes loaded.
Input image filename:/data/tests/generic_detector/car_0.jpg
(416, 416, 3)
clang (LLVM option parsing): Unknown command line argument '-enable-si-insert-waitcnts'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-enable-post-misched'?
MIOpen Error: /data/repo/MIOpen/src/tmp_dir.cpp:18: Can't execute cd /tmp/miopen-MIOpenUtilKernels.cl-9732-80c2-751d-fbfe; /opt/rocm/bin/clang-ocl  -DNUM_CH_PER_WG=1 -DNUM_IM_BLKS_X=13 -DNUM_IM_BLKS=676 -DLOCAL_MEM_SIZE=340 -DSTRIDE_GT_1=0 -DTILE_SZ_X=32 -DTILE_SZ_Y=8 -DUSE_IM_OFF_GUARD=1 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -mcpu=gfx803 -Wno-everything MIOpenUtilKernels.cl -o /tmp/miopen-MIOpenUtilKernels.cl-9732-80c2-751d-fbfe/MIOpenUtilKernels.cl.o
2018-09-28 17:45:26.485140: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1735] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
Aborted (core dumped)
```

**Comment by dagamayank** [comment]
@tadaoisgod What is your system config? How did you install ROCm, which version is it. Seems you somehow have an older version of [clang-ocl](https://github.com/RadeonOpenCompute/clang-ocl) on your system.

**Comment by tadaoisgod** [comment]
@dagamayank I'm using the latest ROCm Docker image, 1.9 stack and 1.10 Tensorflow. Tested on the 1.8 stack too, and got the same error. Is clang-ocl imported from the host machine into the Docker image?

**Comment by Ma-Dan** [comment]
I just test with ROCm 1.9.211, MIOpen 1.5.0 and tensorflow-rocm 1.10.1, get the same error when trying to train inception v1 model which is supplyed by tensorflow itself, with MIOPEN_ENABLE_LOGGING=1, the log is shown below:
```
2018-09-29 10:27:25.527835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1519] Found device 0 with properties:
name: Device 687f
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.59
pciBusID 0000:03:00.0
Total memory: 7.98GiB
Free memory: 7.73GiB
2018-09-29 10:27:25.527862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1630] Adding visible gpu devices: 0
2018-09-29 10:27:25.527876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1039] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-29 10:27:25.527881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045]      0
2018-09-29 10:27:25.527885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1058] 0:   N
2018-09-29 10:27:25.527912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Device 687f, pci bus id: 0000:03:00.0)
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
tensorDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc =
dataType = 1
n = 30
c = 3
h = 225
w = 225
}
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
tensorDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc =
dataType = 1
n = 30
c = 64
h = 112
w = 112
}
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
tensorDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc =
dataType = 1
n = 64
c = 3
h = 7
w = 7
}
MIOpen(HIP): miopenStatus_t miopenCreateConvolutionDescriptor(miopenConvolutionDescriptor_t *){
convDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenInitConvolutionDescriptor(miopenConvolutionDescriptor_t, miopenConvolutionMode_t, int, int, int, int, int, int){
convDesc = miopenConvolution, 0, 0, 1, 1, 1, 1,
c_mode = 0
pad_h = 2
pad_w = 2
u = 2
v = 2
dilation_h = 1
dilation_w = 1
}
MIOpen(HIP): miopenStatus_t miopenConvolutionForwardGetWorkSpaceSize(miopenHandle_t, const miopenTensorDescriptor_t, const miopenTensorDescriptor_t, const miopenConvolutionDescriptor_t, const miopenTensorDescriptor_t, size_t *){
wDesc = 64, 3, 7, 7
yDesc = 30, 64, 112, 112
convDesc = miopenConvolution, 2, 2, 2, 2, 1, 1,
workSpaceSize = 140435107897552
}
MIOpen(HIP): miopenStatus_t miopenFindConvolutionForwardAlgorithm(miopenHandle_t, const miopenTensorDescriptor_t, const void *, const miopenTensorDescriptor_t, const void *, const miopenConvolutionDescriptor_t, const miopenTensorDescriptor_t, void *, const int, int *, miopenConvAlgoPerf_t *, void *, size_t, bool){
xDesc = 30, 3, 225, 225
x = 0x912ac4900
wDesc = 64, 3, 7, 7
w = 0x913c26100
convDesc = miopenConvolution, 2, 2, 2, 2, 1, 1,
yDesc = 30, 64, 112, 112
y = 0x913c2f400
requestAlgoCount = 1
returnedAlgoCount = -1610892993
perfResults =
workSpace = 0x91980f400
workSpaceSize = 7375872
exhaustiveSearch = 0
}
MIOpen(HIP): void miopen::DirConvFindCore(miopen::Handle &, const miopen::TensorDescriptor &, ConstData_t, const miopen::TensorDescriptor &, ConstData_t, const miopen::TensorDescriptor &, Data_t, size_t, const miopen::ConvolutionDescriptor &, bool, miopen::DbRecord &){
"convolution, non 1x1" = convolution, non 1x1
}
MIOpen Error: /data/repo/MIOpen/src/hipoc/hipoc_program.cpp:89: Failed creating module hipErrorUnknown
2018-09-29 10:27:33.357754: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1735] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
Aborted (core dumped)
```

**Comment by sunway513** [comment]
@tadaoisgod , I think the issue is related to your local configuration and environment. Could you try our public docker image?
```
# To configure docker environment
curl -sSL https://get.docker.com/ | sh

# To run TF docker image
alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx -v /data/imagenet/tf:/imagenet'
drun rocm/tensorflow:latest

# To run a cifar10 sample 
cd ~/models/tutorials/image/cifar10 && python3 cifar10_train.py
```

**Comment by sunway513** [comment]
@Ma-Dan I've tried to run the slim inception_v1 test from the following link:
https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v1.py

It can work correctly with our public docker image "rocm/tensorflow", please find the logs attached.
[inception_v1.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2430301/inception_v1.log)

Please let me know if you are using a different model.

**Comment by tadaoisgod** [comment]
I'm using the public image. YOLO uses the [Darknet architecture](https://pjreddie.com/media/files/papers/YOLOv3.pdf).

**Comment by sunway513** [comment]
Hi, could you confirm if the cifar10 sample works correctly using the steps proved above?

**Comment by tadaoisgod** [comment]
It works. I've ran the original image and YOLO training executes perfectly. The error was in my image that used rocm/tensorflow.

Thank you for your attention!

**Comment by Avatat** [comment]
I'm getting this error:
```
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: Im2Col from /home/user/.cache/miopen/1.7.0/00d4f877be81cbdf868b3b496018659c/MIOpenUtilKernels.cl.o hipErrorNotFound
2018-12-24 05:14:48.876215: F tensorflow/stream_executor/rocm/rocm_dnn.cc:2637] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
```
After upgrade from ROCm 1.9.2 to 2.0 on Ubuntu 18.10 with Kernel 4.19.11.
List of upgraded packages:
```
hsa-rocr-dev:amd64 (1.1.9-15-g848be2f, 1.1.9-45-ge88639f), hipsparse:amd64 (0.1.3.1, 1.0.2.0), hsakmt-roct-dev:amd64 (1.0.9-8-g238782c, 1.0.9-99-g3ba20ce), rocblas:amd64 (0.14.3.0, 2.0.0.0), hsakmt-roct:amd64 (1.0.9-8-g238782c, 1.0.9-99-g3ba20ce), rocm-opencl:amd64 (1.2.0-2018111340, 1.2.0-2018121317), libibverbs1:amd64 (19.0-1, 19.0-1ubuntu0.1), hip_base:amd64 (1.5.18442, 1.5.18494), hsa-ext-rocr-dev:amd64 (1.1.9-15-g848be2f, 1.1.9-45-ge88639f), hipblas:amd64 (0.12.1.0, 0.12.1.0), rocfft:amd64 (0.8.6.0, 0.8.8.0), hcc:amd64 (1.2.18451, 1.3.18482), librdmacm1:amd64 (19.0-1, 19.0-1ubuntu0.1), rocr_debug_agent:amd64 (1.0.0, 1.0.0), librdmacm-dev:amd64 (19.0-1, 19.0-1ubuntu0.1), rocm-libs:amd64 (1.9.307, 2.0.89), rocm-dev:amd64 (1.9.307, 2.0.89), rocm-utils:amd64 (1.9.307, 2.0.89), hip_doc:amd64 (1.5.18442, 1.5.18494), miopen-hip:amd64 (1.6.0-ffedda8, 1.7.0-49c48917), rocsparse:amd64 (1.0.1.0, 1.0.1.0), rocm-device-libs:amd64 (0.0.1, 0.0.1), hip_hcc:amd64 (1.5.18442, 1.5.18494), rocm-opencl-dev:amd64 (1.2.0-2018111340, 1.2.0-2018121317), unattended-upgrades:amd64 (1.5ubuntu3, 1.5ubuntu3.18.10.1), hip_samples:amd64 (1.5.18442, 1.5.18494), rocm-smi:amd64 (1.0.0-72-gec1da05, 1.0.0-95-g3512a29),  rocm-profiler:amd64 (5.4.6878, 5.6.7219), cxlactivitylogger:amd64 (5.4.6878, 5.6.7219)
```

/opt/rocm/miopen/include/miopen/version.h:
```
#define MIOPEN_VERSION_MAJOR 1
#define MIOPEN_VERSION_MINOR 7
#define MIOPEN_VERSION_PATCH 0
#define MIOPEN_VERSION_TWEAK 49c48917
```

Before upgrade, everything worked correctly.

**Comment by dagamayank** [comment]
Can you also mention the version of ‘clang-ocl’ package installed on your system?

**Comment by Avatat** [comment]
Now I have `0.3.0-688fe5d` and `tensorflow-rocm` from pip works correctly.

**Comment by daniellowell** [comment]
Please delete you persistent kernel cache located typically in: ~/.cache/miopen
and try the test again. Make sure you path is pointing to the new clang-ocl.

**Comment by Avatat** [comment]
@dagamayank, @daniellowell, thank you for your help, but the problem is solved :) As I wrote, I found ROCmSoftwarePlatform/MIOpen#67 and there was the solution.

But... The problem is, why `apt-get upgrade` didn't upgrade `rocm-clang-ocl` when I upgraded all the packages?

**Comment by daniellowell** [comment]
@Avatat Hmm, good question. Let me check on that.

**Comment by seesturm** [comment]
I'd say that dpkg considers 0.3.0-688fe5d older than 0.3.0-7997136 and therefore does not upgrade (since it is considered a downgrade).

**Comment by Avatat** [comment]
I'm not sure what changed in my environment, but TensorFlow started failing on every model...
I removed rocm* packages, tensorflow-rocm, reinstalled everything and I'm getting this error:
```
2019-01-01 23:37:48.435334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7539 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:05:00.0)
MIOpen Error: /home/dlowell/MIOpenPrivate/src/tmp_dir.cpp:18: Can't execute cd /tmp/miopen-MIOpenUtilKernels.cl-cf91-2ad6-e1bd-b8cd; /opt/rocm/bin/clang-ocl  -DNUM_CH_PER_WG=1 -DNUM_IM_BLKS_X=4 -DNUM_IM_BLKS=64 -DLOCAL_MEM_SIZE=340 -DSTRIDE_GT_1=0 -DTILE_SZ_X=32 -DTILE_SZ_Y=8 -DUSE_IM_OFF_GUARD=1 -DMIOPEN_USE_FP32=1 -mcpu=gfx803 -Wno-everything MIOpenUtilKernels.cl -o /tmp/miopen-MIOpenUtilKernels.cl-cf91-2ad6-e1bd-b8cd/MIOpenUtilKernels.cl.o
2019-01-01 23:37:52.866928: F tensorflow/stream_executor/rocm/rocm_dnn.cc:2637] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
```

**Comment by dagamayank** [comment]
Closing this issue for now, we are working to fix the `clang-ocl` version. Please open a new issue for a new problem.
Thanks for the feedback -- keep 'em coming.
