### ISSUE TITLE
Nightly built wheels from CI doesn't work on Navi 31

### ISSUE THREAD

**Issue by evshiron** [ROCmSoftwarePlatform/tensorflow-upstream#2142]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf_nightly_rocm-2.14.0dev20230628.550-cp310-cp310-manylinux2014_x86_64.whl

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04.2

Tested in ROCm 5.5.1 host and ROCm 5.5.0 container.

### Python version

3.10

### Current Behaviour?

The sample script doesn't work when using `tf-nightly-rocm` from [CI](http://ml-ci.amd.com:21096/job/tensorflow/job/nightly-rocmfork-develop-upstream/job/nightly-build-whl/), which should have Navi 31 support out of the box for the time being.

The log for a previously succeeded run can be found here: https://github.com/RadeonOpenCompute/ROCm/issues/1880#issuecomment-1545193786.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

features = np.random.randn(10000,25)
targets = np.random.randn(10000)

model = tf.keras.Sequential([
     tf.keras.layers.Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.MeanSquaredError())

model.fit(x=features, y=targets)
```

### Relevant log output

```shell
2023-06-29 04:53:06.731832: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-29 04:53:06.755074: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-29 04:53:07.345334: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.352729: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.352755: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353192: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353228: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353254: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353322: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353346: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353374: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-29 04:53:07.353387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1816] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21420 MB memory:  -> device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0
2023-06-29 04:53:07.479918: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:508] ROCm Fusion is enabled.
[SAME LOG TRIMMED]
2023-06-29 04:53:07.677340: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleLoadData(&module, data)' failed with 'hipErrorNoBinaryForGpu'

2023-06-29 04:53:07.677348: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleGetFunction(&function, module, kernel_name)' failed with 'hipErrorInvalidHandle'

2023-06-29 04:53:07.677353: W tensorflow/core/framework/op_kernel.cc:1816] INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
/usr/local/lib/python3.10/dist-packages/keras/src/initializers/initializers.py:120: UserWarning: The initializer GlorotUniform is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
2023-06-29 04:53:07.678085: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleLoadData(&module, data)' failed with 'hipErrorNoBinaryForGpu'

2023-06-29 04:53:07.678093: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleGetFunction(&function, module, kernel_name)' failed with 'hipErrorInvalidHandle'

2023-06-29 04:53:07.678098: W tensorflow/core/framework/op_kernel.cc:1816] INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
Traceback (most recent call last):
  File "/root/test.py", line 14, in <module>
    model.fit(x=features, y=targets)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py", line 52, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.InternalError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1367, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1348, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1125, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/backend.py", line 2102, in random_uniform
        return tf.random.stateless_uniform(

    InternalError: Exception encountered when calling layer 'sequential' (type Sequential).
    
    {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle' [Op:Sub] name: 
    
    Call arguments received by layer 'sequential' (type Sequential):
      • inputs=tf.Tensor(shape=(None, 25), dtype=float32)
      • training=True
      • mask=None
```

**Comment by briansp2020** [comment]
Made some progress building TF for 7900XTX. https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2191
I was able to run a simple example but it leaves my computer in an unstable state, and eventually, GUI crashes.

**Comment by evshiron** [comment]
We have a thread https://github.com/RadeonOpenCompute/ROCm/issues/1880 for it, and after https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2101, TensorFlow should work to some extent. It's even already integrated in their CI. But in your PR there is a missing comma, so I don't know where has it been.

**Comment by briansp2020** [comment]
It looks like [#2101](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2101) is already merged. It's weird that the comma is still missing in the main source.

With the comma added, my build is using the 7900XTX. I still see instability here and there. Hopefully, they will release the working code soon.

**Comment by briansp2020** [comment]
Is anyone else having issues building tf from the source? For me, the build usually fails  2 to 3 times, usually after consuming a lot of memory. Hower, if run the build script again, eventually it completes and generates whl file.

I'm now trying to build using 5.7 environment and the problem seems to be much worse. I retried at least 10 time and it still fails, usually with the following error. But if I retry, it compiles for a while again then crashes.

>>>INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/tensorflow-upstream/tensorflow/compiler/xla/stream_executor/rocm/BUILD:532:11: Compiling tensorflow/compiler/xla/stream_executor/rocm/rocm_helpers.cu.cc failed: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/stream_executor/rocm:rocm_helpers':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/stream_executor/rocm/rocm_helpers.cu.cc':
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_runtime_wrapper.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/cmath'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/stddef.h'
  '/opt/rocm-5.7.0/include/hip/hip_version.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_libdevice_declares.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_math.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/algorithm'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/new'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/limits.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/stdint.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_stdlib.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_cmath.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/complex'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/__stddef_max_align_t.h'
  '/opt/rocm/llvm/lib/clang/17.0.0/include/stdarg.h'
  '/opt/rocm-5.7.0/include/hip/hip_runtime.h'
  '/opt/rocm-5.7.0/include/hip/hip_common.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_runtime.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_common.h'
  '/opt/rocm-5.7.0/include/hip/hip_runtime_api.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/host_defines.h'
  '/opt/rocm-5.7.0/include/hip/driver_types.h'
  '/opt/rocm-5.7.0/include/hip/texture_types.h'
  '/opt/rocm-5.7.0/include/hip/channel_descriptor.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_channel_descriptor.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_vector_types.h'
  '/opt/rocm-5.7.0/include/hip/surface_types.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_runtime_pt_api.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/hip_ldg.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_atomic.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_device_functions.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/math_fwd.h'
  '/opt/rocm-5.7.0/include/hip/hip_vector_types.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/device_library_decls.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_warp_functions.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_unsafe_atomics.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_surface_functions.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/texture_fetch_functions.h'
  '/opt/rocm-5.7.0/include/hip/hip_texture_types.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/ockl_image.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/texture_indirect_functions.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_math_functions.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/hip_fp16_math_fwd.h'
  '/opt/rocm-5.7.0/include/hip/library_types.h'
  '/opt/rocm-5.7.0/include/hip/hip_bfloat16.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_bfloat16.h'
  '/opt/rocm-5.7.0/include/hip/hip_fp16.h'
  '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_fp16.h'
clang++: warning: argument unused during compilation: '-fcuda-flush-denormals-to-zero' [-Wunused-command-line-argument]
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by i-chaochen** [comment]
> Is anyone else having issues building tf from the source? For me, the build usually fails 2 to 3 times, usually after consuming a lot of memory. Hower, if run the build script again, eventually it completes and generates whl file.
> 
> I'm now trying to build using 5.7 environment and the problem seems to be much worse. I retried at least 10 time and it still fails, usually with the following error. But if I retry, it compiles for a while again then crashes.
> 
> > > > INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
> > > > INFO: Found 1 target...
> > > > ERROR: /root/tensorflow-upstream/tensorflow/compiler/xla/stream_executor/rocm/BUILD:532:11: Compiling tensorflow/compiler/xla/stream_executor/rocm/rocm_helpers.cu.cc failed: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/stream_executor/rocm:rocm_helpers':
> > > > this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/stream_executor/rocm/rocm_helpers.cu.cc':
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_runtime_wrapper.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/cmath'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/stddef.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_version.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_libdevice_declares.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_math.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/algorithm'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/new'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/limits.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/stdint.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_stdlib.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_hip_cmath.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers/complex'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/__stddef_max_align_t.h'
> > > > '/opt/rocm/llvm/lib/clang/17.0.0/include/stdarg.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_runtime.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_common.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_runtime.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_common.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_runtime_api.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/host_defines.h'
> > > > '/opt/rocm-5.7.0/include/hip/driver_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/texture_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/channel_descriptor.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_channel_descriptor.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_vector_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/surface_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_runtime_pt_api.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/hip_ldg.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_atomic.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_device_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/math_fwd.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_vector_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/device_library_decls.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_warp_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_unsafe_atomics.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_surface_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/texture_fetch_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_texture_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/ockl_image.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/texture_indirect_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_math_functions.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/hip_fp16_math_fwd.h'
> > > > '/opt/rocm-5.7.0/include/hip/library_types.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_bfloat16.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_bfloat16.h'
> > > > '/opt/rocm-5.7.0/include/hip/hip_fp16.h'
> > > > '/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_fp16.h'
> > > > clang++: warning: argument unused during compilation: '-fcuda-flush-denormals-to-zero' [-Wunused-command-line-argument]
> > > > Target //tensorflow/tools/pip_package:build_pip_package failed to build

seems the build couldn't find rocm stuff at all, I suspect it's related to LLVM version (cannot guarantee).

We recommend you're using rocm/tensorflow-build to build from the source if you want to try
https://hub.docker.com/repository/docker/rocm/tensorflow-build

**Comment by briansp2020** [comment]
To use ROCm 5.7, I changed the ROCM_INSTALL_DIR in build_rocm_python3 to point to /opt/rocm. Making it to point to /opt/rocm-5.7.0 explicitly seems to fix the issue. Not sure why though since /opt/ROCm is a sym-link to the exact same location. 🤷‍♂️

**Comment by i-chaochen** [comment]
> To use ROCm 5.7, I changed the ROCM_INSTALL_DIR in build_rocm_python3 to point to /opt/rocm. Making it to point to /opt/rocm-5.7.0 explicitly seems to fix the issue. Not sure why though since /opt/ROCm is a sym-link to the exact same location. 🤷‍♂️

I am not sure what's your environment, but could you try it in rocm/tensorflow-build ? Thanks

**Comment by briansp2020** [comment]
@i-chaochen 
Can you tell me how to build using rocm/tensorflow-build? I usually build using [build_rocm_python3](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/build_rocm_python3) script in tensorflow-upstream repo. It's not clear to me how to build for rocm using rocm/tensorflow-build.

Thanks!

**Comment by i-chaochen** [comment]
> @i-chaochen Can you tell me how to build using rocm/tensorflow-build? I usually build using [build_rocm_python3](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/build_rocm_python3) script in tensorflow-upstream repo. It's not clear to me how to build for rocm using rocm/tensorflow-build.
> 
> Thanks!

If you installed docker container, then you can follow the instructions from our repo. https://github.com/ROCmSoftwarePlatform/tensorflow-upstream#tensorflow-rocm-port

```
$ alias drun='sudo docker run \
      -it \
      --network=host \
      --device=/dev/kfd \
      --device=/dev/dri \
      --ipc=host \
      --shm-size 16G \
      --group-add video \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      -v $HOME/dockerx:/dockerx'

$ drun rocm/tensorflow-build:latest-python3.9-rocm5.6.0    # for example I am using rocm5.6.0
```

Within the launched container, you can git clone our Tensorflow repo and change the correct rocm-version with directory path in `build_rocm_python3` script and build it.

```
$ git clone https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git
$ cd tensorflow-upstream/
$ ./build_rocm_python3  
```

PS: Because I am using rocm5.6.0 as an example, it's same as in this script. If you're using rocm5.7.0 docker container, you need to change to rocm-5.7.0 as well., e.g., /opt/rocm-5.7.0 in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/build_rocm_python3#L33

**Comment by johnnynunez** [comment]
```
#!/bin/sh

set -ex

sudo apt install -y patchelf

sudo apt-get update && sudo apt-get install -y openjdk-8-jdk openjdk-8-jre unzip wget git libstdc++-12-dev
python3 -m venv venv
python3 -m pip install --upgrade pip

source venv/bin/activate

export WORKDIR=$(pwd)
export PYTHON_BIN_PATH=$WORKDIR/venv/bin/python3
export PYTHON_LIB_PATH=$WORKDIR/venv/lib/python3.11/site-packages
export ROCM_PATH=/opt/rocm-5.7.0
export TF_NEED_ROCM=1
export GPU_DEVICE_TARGETS=gfx1100

# build tensorflow-rocm

if [ -d "tensorflow-upstream" ]; then
    echo "tensorflow-upstream folder exists. Skipping git clone."
else
    git clone --recursive https://github.com/ROCmSoftwarePlatform/tensorflow-upstream
fi
cd tensorflow-upstream

# install bazel in venv
curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64 -o $WORKDIR/venv/bin/bazel \
  && chmod +x $WORKDIR/venv/bin/bazel

bazel clean --expunge

# declare build targets
printf '%s\n' ${GPU_DEVICE_TARGETS} | sudo tee -a $ROCM_PATH/bin/target.lst

# https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/243d98f63f538787b438a15ec0e7cc2f5f9c2d10/tensorflow/tools/ci_build/Dockerfile.rocm#L108
sudo touch $ROCM_PATH/.info/version

pip install setuptools wheel numpy packaging requests

bash build_rocm_python3

cd ..
```
Secondly modify this line. In my case 32gb 16 cores and 32 threads.
```
 RESOURCE_OPTION="--local_ram_resources=60000 --local_cpu_resources=35 --jobs=70"
```
```
RESOURCE_OPTION="--local_ram_resources=28000 --local_cpu_resources=16 --jobs=32"
```

**Comment by lucbruni-amd** [comment]
Hi @briansp2020, @evshiron,

Are you still having issues with this? I know this is an older issue, and we apologize for a lack of checking in. Thanks!

**Comment by briansp2020** [comment]
@lucbruni-amd 
I think prebuilt binary works fine now. So you can close this.

BTW, I tried to build the latest from source and it no longer builds. Has there been some updates which requires additional packages? I'm basically running https://gist.github.com/briansp2020/1e8c3e5735087398ebfd9514f26a0007
The script still runs fine if I try to build 2.15 but it fails compiling 2.16 and up. 

One of the error seems to indicate that I need newer version of llvm. Doesn't ROCm install new version of llvm? Is this some configuration issue or do I need to manually install new version of llvm.

Also, is there a place I can ask questions about building and setting up? Opening an issue feels like I'm abusing the issue tracking. Should I use https://github.com/ROCm/ROCm/discussions? Where can I see the source for building docker that you guys upload to https://hub.docker.com/r/rocm/tensorflow?

Thanks in advance for your reply!

`ERROR: /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/external/com_google_protobuf/BUILD.bazel:364:11: Compiling src/google/protobuf/compiler/command_line_interface.cc [for tool] failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @com_google_protobuf//:protoc_lib)
  (cd /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.d '-frandom-seed=bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o' '-DBAZEL_CURRENT_REPOSITORY="com_google_protobuf"' -iquote external/com_google_protobuf -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/zlib -g0 -w -Wno-sign-compare -g0 '-std=c++17' -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-DTENSORFLOW_USE_ROCM=1' -D__HIP_PLATFORM_AMD__ -DEIGEN_USE_HIP -DUSE_ROCM -no-canonical-prefixes -c external/com_google_protobuf/src/google/protobuf/compiler/command_line_interface.cc -o bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o)
# Configuration: acb2075b49a0e2d868084adfa37322949d23efd7819c4617b76ff41bf820f08d
# Execution platform: @local_execution_config_platform//:platform
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 307, in <module>
    sys.exit(main())
  File "/root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 304, in main
    return subprocess.call([CPU_COMPILER] + cpu_compiler_flags)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/llvm-18/bin/clang'`

**Comment by lucbruni-amd** [comment]
Hi @briansp2020,

Happy to answer some of your questions.

> One of the error seems to indicate that I need newer version of llvm. Doesn't ROCm install new version of llvm? Is this some configuration issue or do I need to manually install new version of llvm.

ROCm does come with our latest fork of llvm under `/opt/rocm/llvm`. Here is a sample from my environment:

```
$ pwd
/opt/rocm/llvm/bin

$ ./clang --version
AMD clang version 18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.3.2 25012 e5bf7e55c91490b07c49d8960fa7983d864936c4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin/.
Configuration file: /opt/rocm-6.3.2/lib/llvm/bin/clang.cfg
```

Are you able to see it?

For the `FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/llvm-18/bin/clang'` error, if you indeed see the clang version installed via your ROCm installation process, do you get further along the build if you symlink `/usr/lib/llvm-18/bin/clang -> /opt/rocm/llvm/bin/clang`?

>Also, is there a place I can ask questions about building and setting up? Opening an issue feels like I'm abusing the issue tracking. Should I use https://github.com/ROCm/ROCm/discussions?

No worries, I think it is fair to have building and setting up questions that may indeed have clear answers for them on the issues page, so users with similar experiences may refer to them and also check their status (open, closed with a resolution, etc.).

Issues are currently being monitored and actioned across ROCm components (including this repository), and we are happy to help with whatever questions you may have, be it a build issue or a complex bug within the component. I appreciate your concern regarding this and I assure you that posting an issue for these things is fine. I would even go further to argue that the discussion board should be used for ongoing, possibly long-term topics that may not even have a clear answer/response.

>Where can I see the source for building docker that you guys upload to https://hub.docker.com/r/rocm/tensorflow?

Inside the container check `cd /tensorflow/tensorflow && git log` which should show the most recent commit SHAs.

**Comment by briansp2020** [comment]
I can build using the docker container from docker hub. But it fails when I use the container I created using https://gist.github.com/briansp2020/b7d40a97a6e809e6aa6ebc7d8e61464f and building using https://gist.github.com/briansp2020/889deca630b9266d82b3a8523e6bfa25
Though the immediate problem is solved, it would be nice to know what's wrong with my docker.

Thank you for your help.

**Comment by lucbruni-amd** [comment]
Hi @briansp2020,

Yeah, I would recommend using the container on the hub for now. I did try your setup of https://gist.github.com/briansp2020/b7d40a97a6e809e6aa6ebc7d8e61464f and building using https://gist.github.com/briansp2020/889deca630b9266d82b3a8523e6bfa25 and got the same error `FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/llvm-18/bin/clang'` from earlier, but for `llvm-17`. I noticed this log

`INFO: Found applicable config definition build:rocm in file /root/tensorflow-upstream/.bazelrc: --config=rocm_base --config=release_cpu_linux_base --action_env=CLANG_COMPILER_PATH=/usr/lib/llvm-17/bin/clang --action_env=TF_ROCM_CLANG=1 --linkopt=-fuse-ld=lld --linkopt=-Wl,--undefined-version --copt=-Wno-gnu-offsetof-extensions --copt=-Wno-unused-result`, so I changed the paths in `/root/tensorflow-upstream/.bazelrc` (there are about 5 of them) to point to `/opt/rocm/llvm/bin/clang` instead, which resolved that error.

Since this issue is unrelated to the OP and the prebuilt binary works now, I'm going to go ahead and close this issue. However, if this is causing you trouble, feel free to open a new issue under this repo and tag me (@lucbruni-amd) and we can work there instead. Thanks!
