### ISSUE TITLE
Any doc/guide for the installation of hovorod for tf-rocm?

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#702]
Any doc/guide for the installation of hovorod for tf-rocm?

Some of my tries were either throwing crash fault during TF runtime, or failed to include the rccl allreduce integration.

**Comment by ghostplant** [comment]
If I directly setup rocmsoftwareplatform/hovorod:hip from source, the tensorflow horovod applications actually crash with following errors:
```sh
..
..
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From ./horovod_tf_mnist.py:30: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From ./horovod_tf_mnist.py:30: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From ./horovod_tf_mnist.py:164: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Fatal Python error: Segmentation fault

Thread 0x00007f191caef740 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/common/basics.py", line 60 in init
  File "./horovod_tf_mnist.py", line 85 in main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250 in _run_main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299 in run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40 in run
  File "./horovod_tf_mnist.py", line 164 in <module>
$
```

**Comment by jeffdaily** [comment]
Which ROCm release did you try?

I build ROCm horovod hip branch using the following env vars:
```
HOROVOD_WITHOUT_MXNET=1
HOROVOD_WITHOUT_PYTORCH=1
HOROVOD_GPU_ROCM=1
HOROVOD_WITH_TENSORFLOW=1
HOROVOD_ROCM_PATH=/opt/rocm
HOROVOD_GPU_ALLREDUCE=NCCL
```

I test using the TF CNN Benchmarks.  This implies I'm using TF 1.15 rather than >= 2.0 since the TF CNN Benchmarks don't support 2.x.

`mpirun -n 8 python3 tf_cnn_benchmarks.py --variable_update=horovod`

**Comment by jeffdaily** [comment]
I have a public docker container based on ROCm 2.9 if you would like to try it.
`jeffdaily/tensorflow:1.15-rocm2.9-ofed4.6-1.0.1.1-py3-mpich3.2.1-horovod`

**Comment by ghostplant** [comment]
@jeffdaily Thanks, I tried your container and it worked. However, it is based on mpich which it not compatible with some of my openmpi-based applications. In the past I just used `openmpi-bin libopenmpi-dev` from ubuntu-18.04 repo and it worked well with CUDA's horovod applications.

I also retried to build rocm's horovod according to your suggestions, and it still has some problem with openmpi:

Install script:
```sh
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_GPU_ROCM=1
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_ROCM_PATH=/opt/rocm
export HOROVOD_GPU_ALLREDUCE=NCCL

git clone --recursive https://github.com/ROCmSoftwarePlatform/horovod --branch hip --single-branch --depth 1

cd horovod && pip3 setup.py install
```

After the installation, just to run the applications in single-gpu mode without the context of mpiexec is OK:
```sh
~/horovod$ python3 ./examples/tensorflow_mnist.py
--------------------------------------------------------------------------
WARNING: There are more than one active ports on host 'amdgpu', but the
default subnet GID prefix was detected on more than one of these
ports.  If these ports are connected to different physical IB
networks, this configuration will fail in Open MPI.  This version of
Open MPI requires that every physically separate IB subnet that is
used between connected MPI processes must have different subnet ID
values.

Please see this FAQ entry for more details:

  http://www.open-mpi.org/faq/?category=openfabrics#ofa-default-subnet-gid

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_default_gid_prefix to 0.
--------------------------------------------------------------------------
AMDGPU ISA: gfx906
memoryClockRate (GHz) 1.725
pciBusID 0000:04:00.0
2019-11-16 06:26:28.433122: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocblas.so
2019-11-16 06:26:28.435480: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libMIOpen.so

(..successfully run..)
```

However, leading the execution with mpiexec would make horovod crash:
```sh
~/horovod$ mpiexec -np 1 --allow-run-as-root --map-by slot --bind-to none -x NCCL_DEBUG=INFO python3 ./examples/tensorflow_mnist.py
Fatal Python error: Segmentation fault

Thread 0x00007f68da9ce740 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/common/basics.py", line 60 in init
  File "./examples/tensorflow_mnist.py", line 81 in main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250 in _run_main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299 in run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40 in run
  File "./examples/tensorflow_mnist.py", line 160 in <module>
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node amdgpu exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by ghostplant** [comment]
I also ensure my environment is clear and correct, because I manual write an nccl op injected to tensorflow and it works correctly with openmpi + rccl + tensorflow 1.14.x.

So can you test on the openmpi cases? I doubt whether the rocm's horovod is compatible with ubuntu's openmpi.

**Comment by jeffdaily** [comment]
I followed most of your instructions and installed openmpi from packages in my ubuntu 16 docker.
`jeffdaily/tensorflow:1.15-rocm2.9-ofed4.6-1.0.1.1-py3-openmpi-horovod`
In the container I could successfully run the trivial TF CNN benchmark using horovod.
```
cd ~/benchmarks/scripts/tf_cnn_benchmarks
mpirun --allow-run-as-root -x NCCL_DEBUG=INFO -n 4 python3 tf_cnn_benchmarks.py --variable_update=horovod
```

**Comment by ghostplant** [comment]
@jeffdaily Maybe it is a bug only happens in ubuntu 18.04, and you can fully reproduce the crash with the following container environment:

```sh
FROM ubuntu:18.04

RUN apt-get update && apt install -y --no-install-recommends git ca-certificates \
    python3-pip python3-wheel python3-setuptools python3-dev python3-pytest \
    vim less netcat-openbsd inetutils-ping curl libopenmpi-dev openmpi-bin kmod \
    cmake g++ libpci3 libnuma-dev gnupg make openssh-server

RUN curl -sL http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    printf "deb [arch=amd64] http://repo.radeon.com/rocm/apt/2.9.0/ xenial main" | tee /etc/apt/sources.list.d/rocm_hip.list && \
    apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    rocm-dev zlib1g-dev unzip llvm-dev rocblas hipsparse rccl rocfft rocrand miopen-hip cxlactivitylogger

RUN pip3 install --user tensorflow-rocm==1.14.3

RUN git clone https://github.com/tensorflow/benchmarks --branch cnn_tf_v1.13_compatible --single-branch --depth 1

ENV HOROVOD_WITHOUT_MXNET=1
ENV HOROVOD_WITHOUT_PYTORCH=1
ENV HOROVOD_GPU_ROCM=1
ENV HOROVOD_WITH_TENSORFLOW=1
ENV HOROVOD_ROCM_PATH=/opt/rocm
ENV HOROVOD_GPU_ALLREDUCE=NCCL

RUN git clone --recursive https://github.com/ROCmSoftwarePlatform/horovod --branch hip --single-branch --depth 1

RUN cd horovod && python3 setup.py install
```

After finishing the build of container, executing `mpirun --allow-run-as-root -x NCCL_DEBUG=INFO -n 4 python3 /benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --variable_update=horovod` will trigger the crash problem.

**Comment by ghostplant** [comment]
And there is no issue running other non-NCCL tensorflow applications.
