### ISSUE TITLE
Multiple memory errors and rocBLAS exception in simple test run

### ISSUE THREAD

**Issue by min0ru** [ROCmSoftwarePlatform/tensorflow-upstream#82]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04.5 LTS
Linux mlfarm 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

rocm version : 1.8.192
rocm-opencl: 1.2.0-2018071109

- **TensorFlow installed from (source or binary)**:
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.8.0-cp35-cp35m-manylinux1_x86_64.whl

- **TensorFlow version (use command below)**:
merge-180607-prev-57-g8d50fe9 1.8.0

- **Python version**: 
Python 3.5.2

- **GPU model and memory**:
6x Vega 64 (1 connected with PCIe 3.0 1x, 5 connected with PCIe 2.0 1x)
Motherboard: asrock b85 anniversary
CPU: Intel(R) Celeron(R) CPU G1830 @ 2.80GHz

- **Exact command to reproduce**:
python -c "import tensorflow as tf; session = tf.Session()"
leads to "failed to allocate *** memory hipError_t(1002) errors"

python tf_example.py 
leads to the same memory errors and crash with error tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed

### Describe the problem

Getting multiple kinds of errors and tensorflow crashes on example code from tensorflow official tutorial:

# tf_example.py file contents:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

============

python tf_example.py

After that python crashes. Check out log provided in attached file 
[tf.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2217462/tf.log)

Key errors you can find in provided log:
E tensorflow/stream_executor/rocm/rocm_driver.cc:734] failed to allocate 7.35G (7889485824 bytes) from device: hipError_t(1002)
E tensorflow/stream_executor/rocm/rocm_blas.cc:358] failed to create rocBLAS handle: rocblas_status_memory_error
W tensorflow/stream_executor/stream.cc:2020] attempting to perform BLAS operation using StreamExecutor without BLAS support

Exception:
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed

I know that rocm by itself does not provide full support of the PCIe 2.0. I used HSA_ENABLE_SDMA=0
environment var to force rocm to work with my configuration. It worked before with other OpenCL application. So i think it is more likely rocm-tensorflow problem by itself.

### Adittional logs/info
[tf.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2217462/tf.log)

/opt/rocm/opencl/bin/x86_64/clinfo output:
[clinfo.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2217464/clinfo.txt)

/opt/rocm/bin/rocminfo output:
[rocminfo.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2217465/rocminfo.txt)

**Comment by whchung** [comment]
@min0ru I think your hardware configuration is invalid for ROCm. The example model works on my test nodes with 2 / 4 / 8 GPU configurations. To run ROCm applications properly, PCIe Gen3 is required. Setting `HSA_ENABLE_SDMA=0` wouldn't help in this case.

**Comment by sunway513** [comment]
@min0ru your CPU (Intel(R) Celeron(R) CPU G1830 @ 2.80GHz) is not in ROCm support list:
https://github.com/RadeonOpenCompute/ROCm#supported-cpus
In addition, your GPUs were connected with 1xPCIE3.0 and 1xPCIE2.0, those are not valid setup for DL anyhow.

**Comment by y-lu** [comment]
Just wanted to report seeing the same problem in ROCM 1.9, even though documentation says it supports PCIe gen2.

Here's my setup:

 System information
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04.1 LTS
Linux mlfarm 4.15.0-35-generic #38-Ubuntu SMP Wed Sep 12 10:38:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
rocm version : 1.9.211
rocm-opencl: 1.2.0-2018090737

* TensorFlow installed from (source or binary):
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow_rocm-1.8.0-cp35-cp35m-manylinux1_x86_64.whl

* Python version:
Python 3.5.2

* GPU model and memory:
6x Vega Frontier Edition (1 connected with PCIe 3.0 1x, 5 connected with PCIe 2.0 1x) + 1x NVIDIA 1080Ti + onboard VGA
Motherboard: Supermicro X10SRL-F
CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

* Exact command to reproduce:
python -c "import tensorflow as tf; session = tf.Session()"
leads to "failed to allocate *** memory hipError_t(1002) errors"

**Comment by y-lu** [comment]
I also tried "export HSA_ENABLE_SDMA=0" before running tensorflow, but it didn't help.

**Comment by y-lu** [comment]
One curious observation: although I have 6 VEGA GPUs, it seems memory errors were only reported for 5 of them.  Is there anyway I can force tensorflow to use only GPU?

**Comment by mxsoftwarelabs** [comment]
Its working for me by not setting n_jobs =-1 at all for rocm's tensorflow keras.

with plaidml i was able to use n_jobs = 4 or -1 where 4 are number of cores on my CPU - strange coz it says its using my graphic card in logs. 

Following was the line of code which was failing: 
`cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)`

**Comment by sunway513** [comment]
Hi @mxsoftwarelabs , I've gone through your logs, it seems the TF training failed because there's already another process has taken all the devices memories:
```
2019-01-08 19:06:10.822532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Vega 10 XL/XT [Radeon RX Vega 56/64], pci bus id: 0000:03:00.0)
2019-01-08 19:06:11.303639: E tensorflow/stream_executor/rocm/rocm_driver.cc:601] failed to allocate 7.35G (7889485824 bytes) from device: hipError_t(1002)
2019-01-08 19:06:11.303736: E tensorflow/stream_executor/rocm/rocm_driver.cc:601] failed to allocate 6.61G (7100536832 bytes) from device: hipError_t(1002)
2019-01-08 19:06:11.303770: E tensorflow/stream_executor/rocm/rocm_driver.cc:601] failed to allocate 5.95G (6390482944 bytes) from device: hipError_t(1002)
```
Could you try our latest 1.12 release and make sure your system is in a clean status?
If issue remains, we need the exact steps to reproduce it locally.

**Comment by sunway513** [comment]
I'm closing this issue, please reopen it if there are further questions.
