### ISSUE TITLE
Error polling for event status: failed to query event: hipError_t(600)

### ISSUE THREAD

**Issue by showlabor** [ROCmSoftwarePlatform/tensorflow-upstream#972]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Here's a very simple example to trigger this error:

```python
import tensorflow as tf

x = tf.constant(2)
y = tf.constant(3)
myquot = tf.divide(x, y)
print("tf.divide(x, y)", myquot.numpy())
```

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Fedora 32, x86_64 using ROCm 3.3.0 rpms from http://repo.radeon.com/rocm/yum/rpm
The same happens on Ubuntu 20.04 LTS, see https://github.com/RadeonOpenCompute/ROCm/issues/1074#issuecomment-626272350

- TensorFlow installed from (source or binary):

Binary (pip3 install --user tensorflow-rocm==2.2.0rc4)

- TensorFlow version (use command below):

v2.2.0-rc2-117-gbca3875 2.2.0-rc4

- Python version:

3.8.2

- GPU model and memory:

Radeon RX580 8GB

**Describe the current behavior**

Running the above code leads to this error:

```
2020-05-14 19:06:43.531958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
2020-05-14 19:06:43.566203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1579] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]     ROCm AMD GPU ISA: gfx803
coreClock: 1.366GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: -1B/s
2020-05-14 19:06:43.610009: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocblas.so
2020-05-14 19:06:43.611542: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libMIOpen.so
2020-05-14 19:06:43.620835: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocfft.so
2020-05-14 19:06:43.632251: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocrand.so
2020-05-14 19:06:43.632388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-14 19:06:43.632700: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
2020-05-14 19:06:43.639185: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3593325000 Hz
2020-05-14 19:06:43.639544: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559d807b7840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 19:06:43.639560: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 19:06:43.640635: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559d80850160 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:
2020-05-14 19:06:43.640645: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Ellesmere [Radeon RX 470/480/570/570X/580/580X/590], AMDGPU ISA version: gfx803
2020-05-14 19:06:43.640737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1579] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]     ROCm AMD GPU ISA: gfx803
coreClock: 1.366GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: -1B/s
2020-05-14 19:06:43.640763: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocblas.so
2020-05-14 19:06:43.640772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libMIOpen.so
2020-05-14 19:06:43.640780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocfft.so
2020-05-14 19:06:43.640788: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocrand.so
2020-05-14 19:06:43.640829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-14 19:06:43.640840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-14 19:06:43.640844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-05-14 19:06:43.640848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-05-14 19:06:43.640910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7459 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590], pci bus id: 0000:09:00.0)
2020-05-14 19:06:43.729783: E tensorflow/stream_executor/rocm/rocm_event.cc:28] Error polling for event status: failed to query event: hipError_t(600)
2020-05-14 19:06:43.729818: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
Abgebrochen (Speicherabzug geschrieben)
```

**Describe the expected behavior**

The code should run without issues.
BTW, the HIP-Examples from https://github.com/ROCm-Developer-Tools/HIP-Examples do run without issues.

**Standalone code to reproduce the issue**

See above.

**Comment by jerryyin** [comment]
I'm not sure if we support a combination of rpm + ubuntu. Could you give the newer docker image with released TF a shot: https://hub.docker.com/r/rocm/tensorflow? Maybe start with `rocm/tensorflow:rocm3.3-tf2.1-dev`

**Comment by showlabor** [comment]
Oh, that's a misunderstanding: It's not a combination of Ubuntu and rpm. I'm only running Fedora and using the published rpms.
Someone else had the same issue on Ubuntu.
Nevertheless, I'll try the Docker image tomorrow.

**Comment by showlabor** [comment]
I didn't have much luck with the docker image, either. Here's what I get *inside the container*:

```
root@yerbouti:/root# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> x = tf.constant(2)
2020-05-18 06:20:33.957399: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
2020-05-18 06:20:33.971389: E tensorflow/stream_executor/rocm/rocm_driver.cc:975] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2020-05-18 06:20:33.976059: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3593380000 Hz
2020-05-18 06:20:33.976365: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3f9fd70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-18 06:20:33.976379: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-18 06:20:33.977180: E tensorflow/stream_executor/rocm/rocm_driver.cc:975] could not retrieve ROCM device count: HIP_ERROR_NoDevice
```

I must admit that I'm not very familiar with docker images and I ran it through podman as docker itself doesn't work on distros using cgroup v2 like Fedora. Here's the command line used adapted from the docker instructions:

```
alias drun='sudo podman run -it --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --shm-size 16G --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx'
drun rocm/tensorflow:rocm3.3-tf2.1-dev
```

I probably still have some kind of a permission problem *in the container* as (after installing kmod in the container) `rocminfo` can't see the graphics card either:

```
/opt/rocm-3.3.0/bin/rocminfo
ROCk module is loaded
fex is member of video group
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 3600 6-Core Processor  
  Marketing Name:          AMD Ryzen 5 3600 6-Core Processor  
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16380888(0xf9f3d8) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16380888(0xf9f3d8) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*** Done ***
```

Any ideas how to continue would be highly appreciated.

Kind regards,
Felix

**Comment by showlabor** [comment]
OK, I got the container running now following this report:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/935

My example is running now without any issues *inside the container*.

Since the container image is using tensorflow-rocm v2.1.0-15-g5466af3d12 2.1.0 on Python 3.6.9 while my host system is running Python 3.8 and tensorflow-rocm v2.2.0-rc2-117-gbca3875 2.2.0-rc4 I gave earlier versions of tensorflow a try in Python 3.7.7 on my host Fedora 32 system.

Results running the simple example from above on directly on my Fedora 32 system *without using a container*:

tensorflow-rocm==2.1.0: working as expected
tensorflow-rocm==2.1.1: working as expected
tensorflow-rocm==2.2.0rc4: Error polling for event status: failed to query event: hipError_t(600)

My RX580 card is  correctly recognized and it is used by tensorflow versions 2.1.0 and 2.1.1.

So there seems to be an issue with the 2.2.0 versions of tensorflow-rocm.

**Comment by jerryyin** [comment]
Thanks for your feedback. This `ROCm` fork of TensorFlow specifically aimed for AMD GPUs. Since you don't have a graphics card (which is exactly what the error message pop up), you may as well go ahead with upstream tensorflow, and its docker [images](https://hub.docker.com/r/tensorflow/tensorflow/tags). Closing the issue now.

**Comment by showlabor** [comment]
Would you, please, reopen this issue: I *do* have a AMD Radeon RX580, see my original report.

```
2020-05-14 19:06:43.531958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
2020-05-14 19:06:43.566203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1579] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]     ROCm AMD GPU ISA: gfx803
```


The card is correctly recognized by rocminfo on my Fedora system. It was just that the container I've used - as you requested - could initally not see it.

After I sorted the container issues out, the RX580 card is correctly used inside the container and in my Fedora system using tensorflow 2.1.0 and 2.1.1.

Still, using tensorflow-rocm 2.2.0 versions yields the "Error polling for event status: failed to query event: hipError_t(600)" message.

**Comment by showlabor** [comment]
I've updated my earlier comments for more clarity, hopefully.

**Comment by jerryyin** [comment]
Reopening for tracking purpose.

@parallelo Could you comment on our support on Fedora RPM based distros?

**Comment by showlabor** [comment]
Thanks!

**Comment by parallelo** [comment]
Hi @showlabor - Thanks for the feedback.  Trying to catch up on the various experiments/results reported in this Issue.  

In general, we currently recommend using [our pre-built TF Docker images](https://hub.docker.com/r/rocm/tensorflow/tags/).  That being said, we are definitely very interested in ironing out any distro portability challenges for our pre-built TF WHLs.  

At this point, it sounds like you are trying to use a `tensorflow-rocm==2.2.0rc4` WHL on a baremetal Fedora 32 system, correct?  (And the same issue happens on Ubuntu 20.04.)  We'll try to reproduce this error locally.

**Comment by pdimh** [comment]
I have exactly the same problem running on Ubuntu 20.04 with the same GPU (RX 580).

**Comment by showlabor** [comment]
> At this point, it sounds like you are trying to use a `tensorflow-rocm==2.2.0rc4` WHL on a baremetal Fedora 32 system, correct? (And the same issue happens on Ubuntu 20.04.) 

Yes, that' a good summary.

> We'll try to reproduce this error locally.

Great, thank you!

**Comment by parallelo** [comment]
We believe we have found the cause of the issue with `tensorflow-rocm==2.2.0rc4`.  Stay tuned..

**Comment by showlabor** [comment]
> We believe we have found the cause of the issue with `tensorflow-rocm==2.2.0rc4`. Stay tuned..

Great! Just in case: I've tried 2.2.0rc2, 2.2.0rc3 as well and the issue was the same. So it didn't start with rc4. But I guess you already knew that.

**Comment by HaromKutya** [comment]
Hi!

I have exactly the same issue for the same python example:
```
2020-05-22 14:52:56.663174: E tensorflow/stream_executor/rocm/rocm_event.cc:28] Error polling for event status: failed to query event: hipError_t(600)
```

I'm using `rocm-libs 3.3.0-19`, and `tensorflow-rocm 2.2.0rc4` in an `Ubuntu 18.04`.
My machine has a Ryzen 5 2600, and a Vega 56 in it.

**Comment by parallelo** [comment]
We believe we've fixed the issues with these release candidates.  On a ROCm 3.3-based environment, can you please give this a try and let us know how it works on your example?
```
pip3 install --user tensorflow-rocm==2.2.0rc5
```
PyPI link:  https://pypi.org/project/tensorflow-rocm/2.2.0rc5/#files

**Comment by showlabor** [comment]
> We believe we've fixed the issues with these release candidates. On a ROCm 3.3-based environment, can you please give this a try and let us know how it works on your example?

Great! Yes, the simple example does run without issues with tensorflow-rocm==2.2.0rc5. Thank you very much!

**Comment by parallelo** [comment]
Happy to hear it!  Thanks for the feedback.
